export { default as Navbar } from './Navbar'
export { default as Card } from './Card'
export { default as Title } from './Title'
export { default as CardsContainer } from './CardsContainer'
export { default as Tab } from './Tab'
export { default as Cover } from './Cover'
export { default as Details } from './Details'
export { default as SimilarItems } from './SimilarItems'